name: Advanced Secure Linux Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secure-build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pip
      run: |
        apt-get update
        apt-get install -y python3-pip
        python3 -m pip install --upgrade pip --no-cache-dir

    - name: Install dependencies
      run: |
        python3 -m pip install --no-cache-dir -r requirements.txt

    - name: Run Dependency Security Scan
      run: |
        python3 -m pip install --no-cache-dir safety
        safety check
